### PR TITLE
adding redesign doc

### PR DESCRIPTION
**Pull request by lamont-granquist**
Thoughts on ruby 2.0 cookbook redesign

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Actually, the recipes I'm writing in my head should all be single-resources with one or two properties.

So I think NO attributes and NO recipes is right.

**Comment by lamont-granquist** [comment]
All stream of consciousness typey-typey as fast as i could so it needs a lot of tightening up now...  I was designing it in my head as I was writing it...

**Comment by lamont-granquist** [comment]
I think the way this could work is in recipe code:

```ruby
ruby # asserts ruby is installed somewhere, returns the path to the bin might be "/usr/bin/ruby" or "/opt/ruby-2.3.0/bin/ruby"
ruby "~> 2.1.0" # asserts a ruby 2.1.x is installed somewhere, returns the path to the bin
```

Those are not resources, they are methods/definitions and it doesn't make sense to hang notifies/subscribes off of them.  They're statements "someone should satisfy this requirement for me" similar to how we don't hang notifies/subscribes off "include_recipe".  In this case, though, if nothing else fires off the install of ruby this may actually wind up taking actions.  But in the general case, it does not.

```ruby
ruby_install "2.1.8"  do
  path "/opt/ruby-2.1.8"
  symlinks "/usr/local"
  gems [ "bundler", "rake", "rspec" ]
end
```

This does a source install into /opt/ruby-2.1.8, drops symlinks into /usr/local and installs some gems.  This is a real resource, can hang notifies/subscribes off of it, etc

**Comment by lamont-granquist** [comment]
the `ruby` method may need to be lazily evaluated at converge time and walk the resource collection (or walk a library helper that accumulates effectively the same information) and return the path to a ruby_install resource that satisfies the requirements.   otherwise, it may just 'queue' up a request in a library and needs to not return the path.

we may need a `ruby_path` helper which takes no actions, but returns the ruby path to the ruby which satisfies the requirements -- but this will necessarily need to be a `lazy {}` LazyEvaluator object.

we might want `ruby_install_binary` and `ruby_install_source` as resources which do the actually work.  that might be flexible enough to sprout ruby_install_rbenv/ruby_install_rmv/ruby_install_chruby resources (in other COOKBOOKs) and not suffer from the chef_ingredient/application cookbook problem of violating interface segregation.  might or might not be an actual ruby_install fascade over the sub-resources.  can't decide if this good design to be flexible in the future, or YAGNI overcomplication...

**Comment by jpruetting** [comment]
@lamont-granquist I'm in the process of reading over everything you've posted so far, but I thought I'd link the cookbook I've been working on in case you haven't seen it: https://github.com/built-by-robots/ruby-cookbook

I agree with a lot of ideas you posted, but I'm not following the part about getting rid of attributes and just using Ruby objects to hold state. Do you know of a cookbook using this technique already or have a quick example to show how it would work?

**Comment by lamont-granquist** [comment]
Nope, its largely in my brain right now...

I need to clean this up because I was designing it as I was typing it and it got messy in between the start and the end as I was figuring out the use cases.  I should also write some user stories.

Its complicated because the pattern is going to look something like an accumulator, but not quite.  I've written lots of accumulator patterns before:

https://github.com/lamont-cookbooks/sk_ssh_known_hosts
https://github.com/lamont-cookbooks/sk_sysctl
https://github.com/lamont-cookbooks/multipackage

But those use definitions, and should probably use straight methods on the DSL instead:

https://github.com/lamont-cookbooks/multipackage/pull/8

But needs to be cleaned up.  Could probably use a params object to hold the parameters which used properties and did actual validation.

Using a PORO library instead of attributes to share state between resources/definitions/methods isn't something that I've implemented before.  Still not certain exactly what it should look like and where the state should go, though.

**Pull request merged**
